// Code generated by protoc-gen-go.
// source: querytube.proto
// DO NOT EDIT!

/*
Package querytube is a generated protocol buffer package.

It is generated from these files:
	querytube.proto

It has these top-level messages:
	QueryParam
	QueryResponse
*/
package querytube

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QueryParam struct {
	Q string `protobuf:"bytes,1,opt,name=q" json:"q,omitempty"`
}

func (m *QueryParam) Reset()                    { *m = QueryParam{} }
func (m *QueryParam) String() string            { return proto.CompactTextString(m) }
func (*QueryParam) ProtoMessage()               {}
func (*QueryParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *QueryParam) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

type QueryResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *QueryResponse) Reset()                    { *m = QueryResponse{} }
func (m *QueryResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()               {}
func (*QueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QueryResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParam)(nil), "QueryParam")
	proto.RegisterType((*QueryResponse)(nil), "QueryResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for QueryTube service

type QueryTubeClient interface {
	Query(ctx context.Context, in *QueryParam, opts ...grpc.CallOption) (*QueryResponse, error)
}

type queryTubeClient struct {
	cc *grpc.ClientConn
}

func NewQueryTubeClient(cc *grpc.ClientConn) QueryTubeClient {
	return &queryTubeClient{cc}
}

func (c *queryTubeClient) Query(ctx context.Context, in *QueryParam, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := grpc.Invoke(ctx, "/QueryTube/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for QueryTube service

type QueryTubeServer interface {
	Query(context.Context, *QueryParam) (*QueryResponse, error)
}

func RegisterQueryTubeServer(s *grpc.Server, srv QueryTubeServer) {
	s.RegisterService(&_QueryTube_serviceDesc, srv)
}

func _QueryTube_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryTubeServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/QueryTube/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryTubeServer).Query(ctx, req.(*QueryParam))
	}
	return interceptor(ctx, in, info, handler)
}

var _QueryTube_serviceDesc = grpc.ServiceDesc{
	ServiceName: "QueryTube",
	HandlerType: (*QueryTubeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _QueryTube_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "querytube.proto",
}

func init() { proto.RegisterFile("querytube.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x2c, 0x4d, 0x2d,
	0xaa, 0x2c, 0x29, 0x4d, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x92, 0xe2, 0xe2, 0x0a,
	0x04, 0x09, 0x05, 0x24, 0x16, 0x25, 0xe6, 0x0a, 0xf1, 0x70, 0x31, 0x16, 0x4a, 0x30, 0x2a, 0x30,
	0x6a, 0x70, 0x06, 0x31, 0x16, 0x2a, 0xc9, 0x73, 0xf1, 0x82, 0xe5, 0x82, 0x52, 0x8b, 0x0b, 0xf2,
	0xf3, 0x8a, 0x53, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0xa0, 0xf2, 0x4c, 0x99, 0x29, 0x46, 0xc6,
	0x5c, 0x9c, 0x60, 0x05, 0x21, 0xa5, 0x49, 0xa9, 0x42, 0x6a, 0x5c, 0xac, 0x60, 0x8e, 0x10, 0xb7,
	0x1e, 0xc2, 0x44, 0x29, 0x3e, 0x3d, 0x14, 0x23, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0x16, 0x1b, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x19, 0xa5, 0xc1, 0xcd, 0x8b, 0x00, 0x00, 0x00,
}
